class ZenConstants {
  // Phân loại Châm ngôn theo Trạng thái tâm lý (Tâm trạng)
  static const Map<String, List<String>> emotionalAffirmations = {
    "burnout": [
      "Sự tồn tại của bạn đã là một món quà. Không cần chứng minh gì cả.",
      "Bạn không cần phải chạy thật nhanh. Đi chậm lại cũng là một sự tiến bộ.",
      "Thành công lớn nhất của hôm nay chỉ đơn giản là bạn đã chăm sóc tốt cho bản thân.",
      "Dịu dàng với chính mình hôm nay. Bạn đang làm rất tốt.",
      "Nghỉ ngơi cũng là một hình thức chuẩn bị cho hành trình phía trước. Đừng cảm thấy tội lỗi.",
      "Bạn là một con người (human being), không phải một cái máy làm việc (human doing). Lắng nghe hơi thở của mình chính là cách bắt đầu lại.",
      "Không cần phải làm mọi thứ thật hoàn hảo. Chấp nhận sự dang dở của hôm nay là một nét đẹp bình dị.",
      "Hơi thở của bạn không vội vã. Nhịp tim của bạn không vội vã. Bạn cũng không cần phải vội vã.",
      "Cho phép bản thân tạm dừng lại là biểu hiện lớn nhất của sự dũng cảm và lòng tự trắc ẩn.",
      "Có những ngày, việc duy nhất bạn cần làm là hít vào thật sâu và thở ra thật nhẹ.",
      "Mọi hoa cỏ đều có mùa nở riêng. Bạn không cần phải nở rộ vào mọi khoảnh khắc.",
      "Sự kiệt sức hôm nay là thông tin từ cơ thể nói rằng bạn đã gồng gánh quá nhiều. Cơ thể cần được lắng nghe và nghỉ ngơi.",
      "Bạn không phải là năng suất công việc của mình. Giá trị của bạn đứng vững khi mọi thứ dừng lại.",
      "Buông lỏng đôi vai đang gồng cứng. Thế giới này sẽ không sụp đổ khi bạn nghỉ ngơi một ngày.",
      "Không cần so sánh chương 1 của mình với chương 20 của người khác. Mỗi người có một nhịp sinh học riêng.",
      "Kiệt sức không phải là thất bại. Nó là tiếng còi báo hiệu bạn cần quay về trú ẩn trong chính mình.",
      "Bạn đủ rồi — ngay trong trạng thái mệt mỏi, rã rời và chưa hoàn thành công việc của hôm nay.",
      "Hôm nay, việc từ chối những kỳ vọng không thuộc về bạn sẽ bảo vệ năng lượng tinh thần của chính bạn.",
      "Trả tự do cho bản thân khỏi áp lực phải luôn tỏ ra mạnh mẽ và có ích.",
      "Một giấc ngủ sâu, một cốc nước ấm — những hành động nhỏ này chính là triết học chữa lành thiết thực nhất.",
      "Bạn không cần cứu thế giới. Sưởi ấm cho chính bản thân mình trước đã là đủ rồi.",
      "Những việc chưa làm xong có thể nằm yên đó. Ngày mai sẽ tự có ánh sáng của ngày mai.",
      "Đôi chân mỏi mệt hôm nay xứng đáng được nâng niu. Lùi lại một bước cũng là một sự lựa chọn tốt.",
      "Cơn kiệt sức này chỉ là thời tiết trong lòng. Nó là tạm thời, không định nghĩa con người bạn.",
      "Không có gì đáng hổ thẹn khi nói 'tôi mệt rồi'. Đó là lúc lòng tự trắc ẩn lên tiếng.",
      "Tháo bỏ lớp mặt nạ bận rộn. Bạn là ai khi không có công việc để làm?",
      "Đứng yên giữa dòng chảy hối hả cũng là một loại bản lĩnh. Bạn được quyền đứng yên.",
      "Năng lượng tinh thần là có hạn. Dành những phần còn lại hôm nay để ôm lấy chính mình.",
      "Sự chấp nhận cơ thể mệt mỏi này là bước đầu tiên để khôi phục sức mạnh nội sinh.",
      "Khi bạn ngừng cố gắng quá sức, bạn mới thực sự thấy mình đang sống."
    ],
    "overthinking": [
      "Chúng ta chỉ có thể kiểm soát cánh buồm, không thể kiểm soát hướng gió. Học cách buông bỏ là cách duy nhất.",
      "Mọi cảm xúc tiêu cực chỉ như mây trôi qua bầu trời tâm trí. Trời rồi sẽ lại xanh.",
      "Quá khứ đã qua, tương lai chưa tới. Sức mạnh của bạn nằm ngay ở giây phút này.",
      "Hôm nay, mọi thứ diễn ra tự nhiên là điều tốt nhất. Mọi sự sắp đặt đều có lý do của nó.",
      "Suy nghĩ chỉ là những làn sóng trên mặt hồ tâm trí. Hồ nước sẽ tự phẳng lặng khi không có gió.",
      "Bạn không phải là suy nghĩ của bạn. Bạn là người đang quan sát những suy nghĩ đó trôi qua.",
      "Suy nghĩ giống như những đám mây. Bạn không cần phải nắm giữ chúng, chúng sẽ tự bay đi.",
      "Mọi lo âu về ngày mai đều là vay mượn từ tương lai một nỗi buồn chưa chắc đã xảy ra.",
      "Bước đi đầu tiên luôn là bước đi quan trọng nhất. Tập trung vào bước chân hiện tại thay vì toàn bộ hành trình giúp ta vững vàng hơn.",
      "Nhìn ngắm một bông hoa hay một tách trà nóng sẽ kéo tâm trí về với cơ thể vật lý của bạn lúc này.",
      "Mọi câu hỏi không nhất thiết phải có câu trả lời ngay lập tức. Sự mơ hồ cũng là một phần của cuộc sống.",
      "Tâm trí đang cố giải quyết những thứ nằm ngoài tầm kiểm soát của nó. Đưa nó về với hiện tại giúp khôi phục sự yên bình.",
      "Những suy nghĩ rối ren chỉ là thông tin cho thấy bạn đang rất quan tâm đến cuộc sống, không phải kẻ thù.",
      "Bạn không cần phải chuẩn bị cho mọi kịch bản tồi tệ nhất. Bạn đủ khả năng ứng phó khi chúng thực sự xảy ra.",
      "Tách biệt giữa suy nghĩ của bạn và sự thật khách quan ngoài kia là điều cần thiết lúc này.",
      "Một suy nghĩ không thể làm tổn thương bạn trừ khi bạn tin vào nó và nuôi dưỡng nó.",
      "Hôm nay, tôi chọn không tranh luận với các kịch bản vẽ ra trong đầu. Tôi chọn cảm nhận thực tại.",
      "Không có quyết định nào hoàn hảo tuyệt đối. Mọi ngã rẽ đều chứa đựng những trải nghiệm riêng.",
      "Trả tự do cho tâm trí khỏi ảo tưởng rằng nghĩ nhiều hơn sẽ giải quyết được tất cả.",
      "Hít một hơi thật sâu. Đếm từ một đến năm. Bạn đang ở đây, an toàn trong khoảnh khắc này.",
      "Những gì xảy ra bên ngoài là vô thường. Pháo đài tâm lý duy nhất nằm ở sự bình yên nội tâm.",
      "Để suy nghĩ tự đối thoại với chính nó, còn bạn tiếp tục thưởng thức bữa tối.",
      "Bạn đang dùng highlight reel của người khác để so sánh với những ngổn ngang sau cánh gà của mình.",
      "Đứng trên cương vị người quan sát. Xem suy nghĩ như những dòng xe cộ trôi qua, đừng nhảy vào làn đường đó.",
      "Tương lai là bức tranh chưa vẽ. Vẽ nó bằng lo âu chỉ làm hỏng đi tấm toan của ngày hôm nay.",
      "Mỗi lần bạn chọn dừng phân tích và tập trung vào một hành động nhỏ, bạn đã tự lấy lại quyền kiểm soát.",
      "Đừng cố sửa chữa mọi suy nghĩ méo mó. Chỉ cần nhận ra sự méo mó đó và mỉm cười đi qua.",
      "Sự mơ hồ của cuộc đời không phải là mối đe dọa, nó là khoảng không cho những khả năng mới.",
      "Bạn đủ rồi — kể cả khi tâm trí bạn hôm nay vẫn chưa tìm được sự bình yên tuyệt đối.",
      "Trả mọi lo lắng về cho vũ trụ. Đêm nay, bạn chỉ cần ngủ một giấc thật ngon."
    ],
    "lonely": [
      "Một hành động tử tế nhỏ bé có thể thắp sáng cả một ngày u ám.",
      "Sâu thẳm bên trong bạn luôn có một nguồn sức mạnh tự thân chưa được khai phá.",
      "Bạn không cô đơn, vũ trụ này đang thở cùng nhịp với bạn.",
      "Bão tố ngoài kia dữ dội đến đâu, sâu thẳm trong lòng vẫn luôn có một nơi tĩnh lặng.",
      "Kết nối chân thành bắt đầu từ việc bạn thấu hiểu và chấp nhận chính sự cô đơn của mình.",
      "Có một bếp lửa ấm áp luôn chờ đón bạn ở đây, trong chốn bình yên này.",
      "Sự cô đơn là khoảng lặng quý giá để bạn làm quen và kết bạn lại với chính con người sâu thẳm của mình.",
      "Mỗi người là một hòn đảo nhỏ, nhưng bên dưới đại dương, chúng ta đều chung một thềm lục địa.",
      "Trò chuyện dịu dàng với nỗi cô đơn như một người bạn cũ lâu ngày gặp lại.",
      "Cảm giác cô độc chỉ là một lời nhắc nhở rằng trái tim bạn đang khao khát những kết nối chân thành.",
      "Luôn có những tâm hồn âm thầm đồng điệu với bạn qua từng trang viết ẩn danh quanh Bếp Lửa này.",
      "Sự cô đơn không nói rằng bạn vô giá trị, nó chỉ cho thấy bạn đang thiếu những kết nối thật lòng.",
      "Bạn cần người khác không phải để được cứu rỗi, mà để nhìn thấy rõ hơn những gì đã có trong bạn.",
      "Làm một điểm tựa vững chãi cho chính mình trước khi tìm kiếm một gậy chống ở bên ngoài.",
      "Cô đơn giữa đám đông là vì bạn đang cố đóng một vai diễn không thuộc về mình. Trở về làm bạn là đủ rồi.",
      "Mọi người quanh bếp lửa này đều đang mang những vết sẹo riêng. Bạn không lẻ loi trong bóng tối.",
      "Khi bạn học được cách ở một mình mà không cô độc, bạn đã nắm giữ chiếc chìa khóa tự do nội tâm.",
      "Một cái ôm thấu cảm gửi đi từ đây có thể sưởi ấm cho ai đó, và đồng thời sưởi ấm chính bạn.",
      "Nỗi cô đơn của hôm nay là tín hiệu để bạn quay vào trong chăm sóc đứa trẻ đang bị lãng quên.",
      "Trải lòng ẩn danh để thấy rằng những nỗi sợ thầm kín nhất của bạn cũng là nỗi sợ của bao người.",
      "Đứng yên trong yên lặng của phòng trống. Bạn vẫn trọn vẹn và có giá trị vô điều kiện.",
      "Sự cô đơn giống như mùa đông. Nó lạnh giá nhưng cần thiết để các hạt mầm bên trong chuẩn bị nảy nở.",
      "Bạn đủ rồi — kể cả khi xung quanh bạn lúc này không có một ai lắng nghe.",
      "Gửi đi hơi ấm vô danh chính là cách bạn nhắc nhở bản thân rằng mình vẫn có khả năng yêu thương.",
      "Mối quan hệ sâu sắc nhất cuộc đời là mối quan hệ giữa bạn với chính bản thân mình.",
      "Không cần phải cố gắng hòa nhập bằng mọi giá. Chấp nhận sự khác biệt của bản thân là bước đầu chữa lành.",
      "Nỗi cô đơn hôm nay là thông tin, không phải bản án chung thân định nghĩa cuộc đời bạn.",
      "Để nỗi buồn cô đơn chảy trôi tự nhiên qua hơi thở. Nó sẽ tự biến đổi khi bạn không chống cự.",
      "Quanh bếp lửa chung này, chúng ta được nhìn thấy nhau trong trạng thái chân thật và nguyên bản nhất.",
      "Khi bạn tự thương lấy mình, sự cô đơn tự khắc chuyển hóa thành sự tĩnh lặng ngọt ngào."
    ],
    "empty": [
      "Trống rỗng không có nghĩa là vô giá trị. Đó là khoảng trống để bạn gieo trồng những hạt mầm mới.",
      "Để tâm trí rỗng lặng như một căn phòng đón nhận làn gió mát buổi sớm mai.",
      "Khi không biết đi đâu, đó là lúc bạn được tự do lựa chọn mọi con đường.",
      "Chấp nhận sự trống trải của thực tại chính là bước đầu tiên để chạm vào sự tự do tối hậu.",
      "Giống như tre rỗng ruột mới tạo nên tiếng sáo du dương, tâm hồn tĩnh lặng mới nghe được âm thanh cuộc sống.",
      "Như một tờ giấy trắng hay một chiếc tách rỗng, sự trống trải mở ra khả năng chứa đựng vô hạn.",
      "Không có gì để mất cũng có nghĩa là bạn đang đứng trước cơ hội để bắt đầu lại mọi thứ theo cách mới.",
      "Cho phép mình được lặng lẽ tồn tại mà không cần gắn nhãn hay định nghĩa bản thân là ai.",
      "Trống rỗng chỉ là một khoảng lặng giữa hai bản nhạc, giúp âm thanh tiếp theo trở nên trong trẻo hơn.",
      "Trong sự tĩnh lặng không màu sắc, bạn sẽ tìm thấy sự tự do nguyên bản nhất của tâm hồn.",
      "Nỗi trống trải hôm nay là thông tin báo hiệu những giá trị bên ngoài đã không còn nuôi dưỡng được bạn.",
      "Không cần vội vã lấp đầy khoảng trống bằng dopamine ngắn hạn. Chỉ cần ngồi yên và cảm nhận nó một lát.",
      "Bạn là ai khi không có mục tiêu để chạy theo, không có kỳ vọng để gồng gánh?",
      "Sự trống rỗng là lời mời gọi quay về với những giá trị tự thân vững chắc nhất.",
      "Không làm gì mà không cảm thấy tội lỗi — đó là lúc bạn chấp nhận giá trị vô điều kiện của sự sinh tồn.",
      "Mọi thứ có thể trôi tuột đi hôm nay. Một tâm hồn rỗng lặng là một tâm hồn không bị giam cầm.",
      "Khi chiếc cúp trống không, nó mới có thể đón nhận nguồn nước mới trong lành.",
      "Trống rỗng không phải là căn bệnh cần chữa trị. Nó là khoảng nghỉ cần thiết trước chu kỳ sinh trưởng mới.",
      "Hôm nay, tôi chọn không cố tỏ ra hạnh phúc hay bận rộn. Tôi chọn ở lại với khoảng lặng này.",
      "Ý nghĩa không được ban sẵn từ vũ trụ. Nó được gieo từ những hạt mầm nhỏ nhất khi lòng bạn đã rỗng.",
      "Bạn đủ rồi — ngay cả khi bạn cảm thấy mình không có mục đích hay động lực gì hôm nay.",
      "Nhìn ngắm khoảng không giữa các kẽ lá sẽ thấy chính khoảng không đó làm nên vẻ đẹp của vòm cây.",
      "Đừng sợ hãi sự vô vị của thực tại. Sự chân thật thường nằm ở những khoảnh khắc giản dị nhất.",
      "Một ngày không đạt được gì vẫn là một ngày trọn vẹn nếu bạn thấy mình đang thở và đang sống thật.",
      "Mọi sự sáng tạo vĩ đại đều bắt đầu từ một khoảng không trống rỗng và im lặng tuyệt đối.",
      "Trả tự do cho bản thân khỏi áp lực phải luôn cảm thấy hào hứng và tràn trề năng lượng.",
      "Lòng rỗng lặng như mặt hồ không gió, phản chiếu bầu trời đêm với tất cả sự chân thật của nó.",
      "Sự trống trải hôm nay chỉ ra rằng bạn cần những nguồn dinh dưỡng sâu sắc hơn cho tâm hồn.",
      "Cảm giác vô định là khởi đầu của sự tự do. Bạn được quyền đi bất cứ hướng nào từ điểm không này.",
      "Mỉm cười chào đón khoảng trống. Đó là nơi bạn được là chính mình mà không cần bất kỳ chiếc mặt nạ nào."
    ],
    "peaceful": [
      "Bình yên không phải là một điểm đến, mà là cách bạn bước đi trong cuộc đời.",
      "Nhìn sâu vào thiên nhiên, bạn sẽ thấu hiểu mọi thứ một cách sâu sắc hơn.",
      "Mỉm cười với hiện tại, trân trọng những điều giản dị quanh mình hôm nay.",
      "Mọi khoảnh khắc trôi qua đều là độc nhất vô nhị. Thưởng thức nó trọn vẹn chính là trân trọng sự sống.",
      "Khi tâm ta bình yên, thế giới xung quanh cũng tự khắc trở nên hiền hòa.",
      "Bình yên không nằm ở một nơi không có tiếng ồn, mà nằm ở sự tĩnh lặng ngay giữa những xáo động.",
      "Trân trọng tia nắng ban mai chiếu qua khung cửa, hay tiếng lá rơi xào xạc bên thềm nhà.",
      "Tâm tĩnh thì nước trong. Mọi thứ lắng xuống tự nhiên như bụi đất trôi về với đất.",
      "Hạnh phúc đơn giản là thấy mình vẫn đang sống, đang thở và được cảm nhận thế giới này.",
      "Khi bạn ngừng tìm kiếm sự hoàn hảo bên ngoài, bạn sẽ thấy sự trọn vẹn trong chính những điều không hoàn hảo.",
      "Bình yên thực sự bắt đầu khi bạn đồng ý sống chung với những gì chưa trọn vẹn của chính mình.",
      "Lòng mình tự do như gió, không vướng bận bởi quá khứ, không lo sợ trước tương lai.",
      "Khoảnh khắc thật là khi bạn không cần phải chứng minh bất kỳ điều gì với bất kỳ ai.",
      "Nhìn sâu vào tách trà ấm. Cảm nhận hơi nóng tỏa ra. Bạn đang ở đây, trọn vẹn và bình yên.",
      "Không có cơn bão nào kéo dài mãi mãi. Sự bình yên bên trong là mỏ neo giữ bạn đứng vững.",
      "Khi bạn chấp nhận số phận với sự bình thản tối đa (Amor Fati), mọi biến cố chỉ là chất liệu để trưởng thành.",
      "Sự tĩnh lặng giữa lòng thành phố không nằm ở không gian, nó nằm ở thái độ đón nhận của bạn.",
      "Bạn đủ rồi — không cần thêm bất kỳ điều kiện nào để được quyền cảm thấy bình an ngay lúc này.",
      "Mỉm cười trước những điều không như ý. Chấp nhận sự vô thường là chìa khóa của tự do nội tâm.",
      "Một hành động nhỏ làm với sự chú tâm trọn vẹn chính là một nghi lễ nuôi dưỡng tâm hồn.",
      "Thay vì đuổi theo những kích thích dopamine ngắn hạn, việc nuôi dưỡng những bình lặng bền bỉ sâu bên trong mang lại giá trị lâu dài hơn.",
      "Nhìn mọi thứ trôi qua với tâm thế người lữ hành. Không chiếm hữu, không phán xét, chỉ trân trọng.",
      "Sự thấu hiểu bản thân là cội nguồn của mọi sự yên bình đích thực.",
      "Để lại sau lưng những ồn ào của thế giới số. Lắng nghe tiếng chim hót bên thềm.",
      "Bạn có giá trị vô điều kiện. Nhận thức này mang lại sự giải thoát lớn nhất khỏi mọi lo âu.",
      "Cơ thể và tâm trí hòa làm một khi ta chú tâm vào từng bước đi chạm nhẹ trên mặt đất.",
      "Khi bạn ngừng so sánh cuộc đời mình với người khác, bình yên sẽ tự gõ cửa tìm về.",
      "Nỗi buồn hay niềm vui đều là những vị khách ghé thăm. Đối đãi với chúng bằng lòng hiếu khách bình thản giúp lòng nhẹ nhàng hơn.",
      "Cảm ơn những khoảng lặng tĩnh mịch của đêm nay, nơi bạn được hòa nhịp với hơi thở của đất trời.",
      "Thứ bạn đang tìm kiếm không nằm ở phía trước. Nó đã có trong bạn — đang chờ được nhận ra."
    ]
  };

  // Danh sách phẳng để duy trì khả năng tương thích ngược
  static final List<String> dailyAffirmations = emotionalAffirmations.values.expand((list) => list).toList();

  // Danh sách các hành động nhỏ (Micro-offerings) chữa lành phong phú
  static const List<Map<String, dynamic>> microOfferings = [
    {
      "id": "water",
      "title": "Uống một ly nước đầy",
      "description": "Uống thật chậm rãi, cảm nhận sự tươi mát thấm vào từng tế bào cơ thể.",
      "duration": "1 phút",
      "points": 5,
      "category": "body",
      "icon": "water_drop",
    },
    {
      "id": "breathe",
      "title": "5 hơi thở chánh niệm sâu",
      "description": "Hít vào bụng phình nhẹ, thở ra bụng xẹp dần. Tập trung hoàn toàn vào luồng khí.",
      "duration": "2 phút",
      "points": 5,
      "category": "mind",
      "icon": "air",
    },
    {
      "id": "tidy_desk",
      "title": "Dọn dẹp lại góc làm việc",
      "description": "Sắp xếp lại 3 món đồ trên bàn để tạo không gian ngăn nắp và thoáng đãng mới.",
      "duration": "5 phút",
      "points": 10,
      "category": "body",
      "icon": "cleaning_services",
    },
    {
      "id": "gratitude_msg",
      "title": "Gửi một tin nhắn cảm ơn",
      "description": "Gửi lời cảm ơn chân thành đến một người bạn hoặc người thân không vì lý do cụ thể nào.",
      "duration": "3 phút",
      "points": 15,
      "category": "soul",
      "icon": "sms",
    },
    {
      "id": "nature_look",
      "title": "Ngắm nhìn một nhành cây",
      "description": "Nhìn ra cửa sổ, tập trung quan sát một nhành lá hay đóa hoa đu đưa trước gió trong 2 phút.",
      "duration": "2 phút",
      "points": 5,
      "category": "mind",
      "icon": "yard",
    },
    {
      "id": "stretch",
      "title": "Vươn vai thả lỏng cơ thể",
      "description": "Đứng dậy vươn người cao hết cỡ, xoay nhẹ cổ và khớp vai để giải phóng stress tích tụ.",
      "duration": "3 phút",
      "points": 8,
      "category": "body",
      "icon": "accessibility",
    },
    {
      "id": "confess_burn",
      "title": "Gửi nỗi lo vào hư vô",
      "description": "Viết ra 1 điều làm bạn mệt mỏi nhất hôm nay vào 'Khoảng Buông' và gửi nó vào hư vô.",
      "duration": "3 phút",
      "points": 10,
      "category": "mind",
      "icon": "cloud_queue",
    },
    {
      "id": "empathy_hug",
      "title": "Gửi một cái ôm vô danh",
      "description": "Vào khu vực 'Bếp Lửa Chung', đọc tâm sự của một người lạ và nhấn nút 'Sưởi ấm' họ.",
      "duration": "2 phút",
      "points": 15,
      "category": "soul",
      "icon": "favorite",
    },
  ];

  // Danh sách 60 câu châm ngôn sưởi ấm cho Bếp lửa sưởi ấm ở HomeView
  static const List<String> hearthQuotes = [
    "Hôm nay, dù thế giới ngoài kia có xô bồ và lạnh lẽo thế nào, bạn luôn có một chốn nương tựa ở đây.",
    "Bạn không cần phải luôn tỏ ra mạnh mẽ. Đôi khi, chấp nhận sự yếu đuối của mình mới là bản lĩnh thực sự.",
    "Hơi ấm của bếp lửa này được thắp lên từ chính những tổn thương đang được chữa lành của bạn.",
    "Một ngày bình thường trôi qua không có nghĩa là vô ích. Tồn tại một cách bình yên đã là một thành tựu lớn.",
    "Thế giới ngoài kia đo lường bạn bằng thành tích, còn ở đây, chúng tôi trân trọng sự hiện diện chân thật của bạn.",
    "Bạn đủ rồi — ngay trong khoảnh khắc này, với tất cả những ngổn ngang và những điều chưa hoàn thiện.",
    "Những ồn ào của ngày hôm nay có thể lắng xuống. Đêm nay, bạn chỉ cần ở lại với hơi ấm của chính mình.",
    "Sự bình yên không nằm ở việc trốn chạy giông bão, mà nằm ở việc tìm thấy mỏ neo vững chắc ngay bên trong bạn.",
    "Đừng để tiếng ồn bên ngoài lấn át đi những tiếng nói thầm thì, chân thật nhất từ con người sâu thẳm của bạn.",
    "Mỗi vết sẹo bạn mang theo đều là bằng chứng cho thấy bạn đã dũng cảm đi qua những ngày giông bão.",
    "Bếp lửa này không phán xét bạn. Cởi bỏ chiếc mặt nạ bận rộn và ngồi xuống sưởi ấm đôi bàn tay.",
    "Có những ngày, việc duy nhất bạn cần làm là hít vào thật sâu và thở ra thật nhẹ để nhận ra mình đang sống.",
    "Bạn là người lữ hành trên con đường của riêng mình. Không có người đi trước, không có người đi sau, chỉ có bạn.",
    "Nhìn ngắm ánh lửa bập bùng và nhận ra rằng: Mọi nỗi đau rồi cũng sẽ hóa nhạt và trôi vào hư vô.",
    "Giá trị của bạn là vô điều kiện. Không một ai, không một thành công hay thất bại nào có thể định nghĩa được bạn.",
    "Học cách trân trọng những góc tối, những ngày buồn bã giúp tạo nên sự trọn vẹn của bạn.",
    "Sự kết nối chân thành nhất bắt đầu từ việc bạn biết cách dịu dàng ôm lấy nỗi cô đơn của chính mình.",
    "Một hành động nhỏ chăm sóc bản thân hôm nay là minh chứng rõ nhất cho việc bạn đang trân trọng sự sống này.",
    "Không có con đường nào là sai lầm nếu nó đưa bạn trở về gần hơn với con người nguyên bản của mình.",
    "Bạn không đơn độc. Luôn có những tâm hồn âm thầm ngồi quanh bếp lửa này, chia sẻ cùng tần số cảm xúc với bạn.",
    "Trà ấm đã pha, bếp lửa đã đượm. Tâm trí xứng đáng được nghỉ ngơi một lúc sau một ngày dài.",
    "Nhịp sống hối hả ngoài kia là của thế giới. Nhịp thở tĩnh lặng này là của riêng bạn.",
    "Sự dịu dàng với bản thân cũng giống như cách bạn dịu dàng với một người bạn đang gặp khó khăn.",
    "Cơn mưa ngoài cửa sổ rồi sẽ tạnh, và những xáo động trong lòng bạn cũng sẽ tự tìm về trạng thái bình yên.",
    "Mọi sự thay đổi sâu sắc nhất đều bắt đầu một cách lặng lẽ từ bên trong, không cần ai nhìn thấy.",
    "Bạn không cần phải giải thích hay chứng minh giá trị của mình với bất kỳ ai. Bạn sinh ra là đã đủ giá trị.",
    "Để cuộc đời trôi chảy tự nhiên. Đôi khi, buông bỏ việc kiểm soát chính là cách tìm thấy sự tự do.",
    "Những suy nghĩ ngổn ngang hôm nay chỉ là thời tiết nhất thời. Bầu trời tâm trí bạn vẫn luôn xanh.",
    "Cảm ơn bạn vì đã kiên trì đi qua ngày hôm nay, kể cả khi có những lúc bạn tưởng chừng muốn bỏ cuộc.",
    "Dành ra vài phút yên lặng không làm gì cả. Đó là món quà tuyệt vời nhất bạn có thể tự tặng mình lúc này.",
    "Đừng so sánh behind-the-scenes ngổn ngang của mình với highlight reel lấp lánh của người khác.",
    "Mọi cảm xúc khó chịu chỉ là thông tin cho thấy bạn đang cần được yêu thương và vỗ về nhiều hơn.",
    "Sự trống trải trong lòng không phải là điều đáng sợ, đó là khoảng trống để bạn gieo những hạt mầm mới.",
    "Trân trọng cả những ngày bản thân cảm thấy mệt mỏi hay vô dụng nhất, vì đó là lúc tâm hồn đang cần nghỉ ngơi.",
    "Bếp lửa này luôn cháy sáng bằng sự đồng cảm thầm lặng của những tâm hồn cùng tần số.",
    "Đứng yên giữa dòng người vội vã cũng là một loại tự do. Bạn không nhất thiết phải cuốn theo họ.",
    "Giá trị của bạn không tăng khi bạn làm tốt và không giảm khi bạn phạm sai lầm. Bạn là duy nhất.",
    "Cơ thể này xứng đáng nhận được một lời cảm ơn vì đã gánh vác mọi mệt mỏi để đưa bạn đi qua ngày hôm nay.",
    "Một góc nhỏ bình yên ở đây luôn mở cửa đón chào bạn quay về, không điều kiện, không phán xét.",
    "Những lo lắng có thể trôi vào hư vô theo từng hơi thở ra thật chậm, thật nhẹ.",
    "Bạn không cần phải hoàn hảo để được yêu thương. Những mảnh vỡ cũng có nét đẹp wabi-sabi của riêng nó.",
    "Khi bạn ngừng đòi hỏi cuộc đời phải dễ dàng hơn, bạn sẽ thấy mình mạnh mẽ hơn rất nhiều.",
    "Đi tìm ý nghĩa từ những điều nhỏ bé nhất: một nụ cười ấm áp, một tách trà thơm, một hơi thở nhẹ.",
    "Bạn là người quan sát những cảm xúc trôi qua, chứ không phải chính những cảm xúc đó. Sự vững chãi nằm ở đó.",
    "Những kỳ vọng của xã hội có thể rơi rụng bên ngoài cánh cửa. Ở đây, bạn chỉ cần là chính mình.",
    "Sự tĩnh lặng nội tâm là pháo đài vững chắc nhất giúp bạn đi qua mọi giông bão cuộc đời.",
    "Cảm xúc khó chịu không phải là lỗi của bạn. Nó chỉ là một vị khách ghé thăm rồi sẽ lại rời đi.",
    "Nhìn lại chặng đường đã qua để thấy bạn đã dũng cảm vượt qua bao nhiêu điều tưởng chừng không thể.",
    "Cho phép bản thân được sai, được làm lại, và được bắt đầu lại từ bất kỳ thời điểm nào.",
    "Hơi ấm từ bếp lửa thấu cảm này luôn sẵn sàng ôm lấy bạn mỗi khi bạn cảm thấy thế giới quá lạnh lùng.",
    "Tương lai là bức tranh chưa vẽ, đừng dùng lo âu của hiện tại để tô màu u ám lên nó.",
    "Chậm lại một nhịp để cảm nhận mặt đất dưới chân vững chãi nâng đỡ bạn từng bước đi.",
    "Bạn đang làm tốt hơn những gì bạn nghĩ. Tin tưởng vào tiến trình tự chữa lành của bản thân là chìa khóa.",
    "Khi bạn tự thương lấy mình, cả thế giới xung quanh bỗng nhiên cũng trở nên dịu dàng hơn.",
    "Để lại sau lưng những gì không thể thay đổi và tập trung năng lượng vào giây phút hiện tại này.",
    "Những chia sẻ vô danh quanh bếp lửa là lời nhắc nhở rằng chúng ta luôn đồng hành cùng nhau trong nỗi đau.",
    "Trút bỏ gánh nặng phải làm hài lòng tất cả mọi người. Người đầu tiên bạn cần trân trọng là chính mình.",
    "Để tâm hồn mình rỗng lặng như một căn phòng sạch sẽ, sẵn sàng đón nhận những điều lành mạnh mới.",
    "Sự bình yên đích thực không nằm ở bên ngoài, nó đã có sẵn trong bạn, chỉ chờ bạn nhận ra và tin vào.",
    "Chúc bạn có một giấc ngủ bình yên đêm nay, để ngày mai lại bắt đầu với một tâm thế nhẹ nhàng, nội sinh."
  ];

  // Danh sách các câu hỏi tự vấn sâu sắc (Reflection Prompts)
  static const List<String> reflectionPrompts = [
    "Bạn là ai khi không có ai nhìn?",
    "Bạn đủ rồi chưa — ngay lúc này, trong trạng thái này?",
    "Thứ gì đang thực sự nuôi dưỡng bạn — không phải kích thích bạn?",
    "Đâu là ranh giới giữa việc kiên trì cố gắng và việc gồng gánh quá sức chịu đựng?",
    "Nếu tách biệt suy nghĩ của bạn ra khỏi sự thật khách quan, điều gì thực sự còn lại?",
    "Nỗi cô đơn đang cố gắng báo hiệu cho bạn về nhu cầu kết nối nào chưa được đáp ứng?",
    "Khoảng trống rỗng trong lòng bạn hôm nay đang mở ra cơ hội để gieo trồng hạt mầm mới nào?",
    "Khoảnh khắc bình an nhỏ bé nhất bạn cảm nhận được ngày hôm nay trông như thế nào?"
  ];
}
